# Generated by Django 6.0.2 on 2026-04-24 15:40

import django.db.models.deletion
import django_attachments.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0001_initial'),
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=40)),
                ('image', django_attachments.fields.SingleImageField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_image', to='django_attachments.library')),
            ],
        ),
    ]
