# Generated by Django 5.0.6 on 2026-02-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0001_initial'),
    ]

    operations = []
