# Generated by Django 5.0.6 on 2026-02-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0002_user'),
    ]

    operations = []
