# Generated by Django 6.0.4 on 2026-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt_es', models.TextField(help_text='Resumen corto en español (1-2 oraciones).')),
                ('excerpt_en', models.TextField(help_text='Short summary in English (1-2 sentences).')),
                ('content_json_es', models.JSONField(blank=True, default=dict, help_text='Structured content (Spanish): {intro, sections[], conclusion}.')),
                ('content_json_en', models.JSONField(blank=True, default=dict, help_text='Structured content (English): {intro, sections[], conclusion}.')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/')),
                ('category', models.CharField(blank=True, choices=[('ai-quality', 'AI Quality'), ('localization', 'Localization'), ('case-study', 'Case Study'), ('industry', 'Industry'), ('operations', 'Operations')], default='', max_length=50)),
                ('author', models.CharField(choices=[('xpandia-team', 'Xpandia Team')], default='xpandia-team', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
