# Generated by Django 6.0.4 on 2026-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', help_text='External cover image URL. Takes precedence over an uploaded file.', max_length=500),
        ),
    ]
